[package]
name = "bevy_egui"
version = "0.7.1"
authors = ["mvlabat <mvlabat@gmail.com>"]
description = "A plugin for Egui integration into Bevy"
license = "MIT"
edition = "2018"
repository = "https://github.com/mvlabat/bevy_egui"
exclude = ["assets/**/*", ".github/**/*"]
resolver = "2"

[package.metadata.docs.rs]
no-default-features = true # clipboard crate fails the build currently https://github.com/rust-lang/docs.rs/issues/695

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["manage_clipboard", "open_url"]
manage_clipboard = ["clipboard", "thread_local"]
open_url = ["webbrowser"]

[dependencies]
bevy = { version = "0.5", default-features = false, features = [
    "bevy_render2",
    "bevy_winit",
    "bevy_core_pipeline"
]}
egui = "0.14.0"
webbrowser = { version = "0.5.5", optional = true }
winit = { version = "0.25.0", features = ["x11"], default-features = false }
bytemuck = { version = "1.7.0", features = ["derive"] }
wgpu = "0.11.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clipboard = { version = "0.5.0", optional = true }
thread_local = { version = "1.1.0", optional = true }

[dev-dependencies]
version-sync = "0.9.2"


[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
bevy = { version = "0.5", default-features = false, features = [
	"bevy_wgpu",
	"x11",
	"png"
] }

[patch.crates-io]
#bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy = { path = "../bevy" }
